import { useEffect, useState } from 'react';
import { DialogueBox } from './DialogueBox';
export type BattleMove = { code: string; label: string; correct: boolean; explanation: string };
export type BattleEncounter = { id: string; name: string; foe: string; prompt: string; moves: BattleMove[]; reward: number };
type BattleStageProps = { encounter: BattleEncounter; coachText: string | null; onCoach: (kind: 'hint' | 'explain') => void; onTurn: () => void; onVictory: () => void; onExit: () => void; onSound: (name: 'select' | 'impact' | 'win' | 'error') => void };
export const BattleStage = ({ encounter, coachText, onCoach, onTurn, onVictory, onExit, onSound }: BattleStageProps) => {
  const [foeHp, setFoeHp] = useState(3); const [message, setMessage] = useState('Pick a Python move. Correct code powers your signal.'); const [won, setWon] = useState(false);
  useEffect(() => { setFoeHp(3); setWon(false); setMessage('Pick a Python move. Correct code powers your signal.'); }, [encounter.id]);
  const useMove = (move: BattleMove) => { onTurn(); if (!move.correct) { onSound('error'); setMessage(`That move fizzled. ${move.explanation}`); return; } onSound('impact'); const nextHp = foeHp - 1; setFoeHp(nextHp); if (nextHp <= 0) { setWon(true); onSound('win'); setMessage(`${encounter.foe} is calm again. Bytebrook brightens.`); onVictory(); } else setMessage(`Clean hit! ${move.explanation} One more signal should do it.`); };
  return <section className="battle-stage" aria-label={`${encounter.name} battle`}><header className="battle-topbar"><button type="button" className="quiet-button" onClick={onExit}>← Village</button><span>BYTEBROOK / {encounter.name}</span><span>HP {foeHp}/3</span></header><div className="battle-field"><div className="battle-foe"><div className="foe-sprite" aria-hidden="true" /><p>{encounter.foe}</p><div className="hp"><i style={{ width: `${foeHp / 3 * 100}%` }} /></div></div><div className="battle-hero"><div className="hero-sprite" aria-hidden="true" /><p>YOU</p></div></div><DialogueBox speaker="Nova">{won ? <><p>{message}</p><button className="pixel-button primary" type="button" onClick={onExit}>Return to Bytebrook</button></> : <><p>{encounter.prompt}</p><p className="battle-message">{message}</p></>}</DialogueBox>{!won && <div className="move-tray"><p>CODE MOVES</p>{encounter.moves.map((move) => <button key={move.code} className="code-move" type="button" onClick={() => useMove(move)}><code>{move.code}</code><span>{move.label}</span></button>)}</div>}{!won && <aside className="coach-tray"><p>STUDY PAL</p><button type="button" onClick={() => onCoach('hint')}>Hint</button><button type="button" onClick={() => onCoach('explain')}>Explain</button>{coachText && <p className="coach-copy">{coachText}</p>}</aside>}</section>;
};
